### ISSUE TITLE
Shadow theme components and styles missing in production build when themesDir is provided

### ISSUE THREAD

**Issue by mrfelton** [doczjs/docz#1105]
## Bug Report

Seems like the issue in https://github.com/doczjs/docz/issues/1056 may not have been fully resolved. Still some things are not being set up properly in a production build.

It's ok if you run `yarn dev` before you build and serve, but if you don't then some things are missing from the production build, such as shadowed theme components and styles.

**To Reproduce**

Compare:
```sh
git clone https://github.com/LN-Zap/zap-tutorials
cd zap-tutorials
yarn develop
```
with:
```sh
git clone https://github.com/LN-Zap/zap-tutorials
cd zap-tutorials
yarn build
yarn serve
```

Notice that the header looks completely different - this is because the shadow components and styles are missing if you don't `dev` before you `build`.

**Comment by rubencustodio** [comment]
I am also facing this issue and I won't be able to build a production version until this is fixed. My shadow components are based on my company's style guide and it won't look correct without it.

**Comment by rakannimer** [comment]
Hey,

As @brandonarbini said in #967 the issue is that docz is not copying the base directory (defaults to `src`) to the `.docz` directory before building and relying on dev being called before build.

If someone would like to submit a PR to fix it I'd be happy to help/review/merge.

If you can't, no problem. I'll get to it later this week !

**Comment by rakannimer** [comment]
Hey this was fixed in [2.0.0-rc.42]
(https://github.com/doczjs/docz/releases/tag/v2.0.0-rc.42)

Could you give the latest rc a try ?

**Comment by mrfelton** [comment]
Hi,

No this still doesn't work correctly.

Compare a build of https://github.com/LN-Zap/zap-tutorials with/without doing `yarn dev` first.

**Comment by rakannimer** [comment]
Should be fixed in 2.0.0-rc.51 tried zap-tutorials locally with it and it worked. Could you confirm ?

**Comment by rakannimer** [comment]
Hmmm I think the update didn't go right, here's what it looks like after running yarn add docz@next on my installation :  

<img width="357" alt="Screen Shot 2019-09-30 at 5 00 26 PM" src="https://user-images.githubusercontent.com/1270909/65916733-dee16a80-e3a3-11e9-94ad-8afea6f69cc3.png">


Could you try removing your yarn.lock file .docz folder and node_modules and trying again ?

```sh
rm -rf .docz node_modules yarn.lock && yarn add docz@next && yarn docz build && yarn docz serve
```

**Comment by mrfelton** [comment]
Ok, my bad. I guess I had a stale lock file and some old deps. Looks good now. Thanks for working on this 👍

**Comment by simonrelet** [comment]
Hello,

It looks like the issue is still here when the `themesDir` option in _doczrc.js_ is set to a value other than `'src'`. After investigation I think it is caused by [this line](https://github.com/doczjs/docz/blob/master/core/docz-core/src/bundler/machine/actions.ts#L30) in which _gatsby-theme-docz_ is copied to docz's folder but `themesDir` is preserved in the destination path instead of coping it to _.docz/src/_.

For example:

```js
// doczrc.js
export default {
  // ...
  themesDir: 'theme',
  // ...
}
```

Will give the following structure:

```
.
├─┬ .docz/
│ ├── src/
│ └─┬ theme/
│   └── gatsby-theme-docz/
├── src/
└─┬ theme/
  └── gatsby-theme-docz/
```

_theme/gatsby-theme-docz/_ is copied to _.docz/theme/gatsby-theme-docz/_ instead of _.docz/src/gatsby-theme-docz/_.

I can submit a PR to fix it if it helps.

**Comment by rakannimer** [comment]
Hey @simonrelet 

Thanks for reporting this, a PR would be great ! 

> It looks like the issue is still here when the themesDir option in doczrc.js is > set to a value other than 'src'. After investigation I think it is caused by this line  in which gatsby-theme-docz is copied to docz's folder but themesDir is > preserved in the destination path instead of coping it to .docz/src/.

I agree 👍 

Feel free to join the project's slack if you have any questions or face an issue while submitting : [slack link](https://join.slack.com/t/docz-workspace/shared_invite/enQtNzc4ODc2ODA3NzUxLWI0ZmYwY2NhNjhkNDFjN2UzYzlmMDcwZjQyZGY4MWQ1NmQwZDVlZDE4MmE3N2I4MWRjZTAxZjY4ODk4NGMzZjg).

**Comment by rakannimer** [comment]
This should be fixed by @simonrelet's PR released in `2.0.0-rc.64`. 

Versions >= [`2.0.0-rc.64`](https://github.com/doczjs/docz/releases/tag/v2.0.0-rc.64) should work as expected. Going to close this, please feel free to re-open if it occurs again.
